### ISSUE TITLE
isort inconsistencies for the same version but different Python versions

### ISSUE THREAD

**Issue by jbaublitz** [timothycrosley/isort#1006]
I've run into a bit of a puzzle and am not entirely sure what's going on. It seems extremely similar to #379, but reversed this time. I'm currently using isort version 4.3.4, and I've managed to reproduce [this failure case](https://travis-ci.org/stratis-storage/stratis-cli/jobs/578398310) only when downgrading to Python 3.7.1 from Python 3.7.4 locally.

This error doesn't make a whole lot of sense as it only occurs under Python 3.7.1. If this condition is not met, I can't reproduce this. I understand this probably a pretty low priority bug because it is only reproducible for me under such specific circumstances, but do you have any idea what might be going on? Interestingly, the formatter `yapf` had a very similar problem when jumping between these versions and I'm not sure if both of these projects use a feature that has changed between those two versions that you're aware of?

**Comment by jcollado** [comment]
Just in case this is useful, I had a similar problem in which I was getting a different result in the CI environment and in tox. In the end, what was different was that in the CI environment the package was installed in development mode and in tox it wasn't.

In this case, the fix was either telling `isort` that my package was a known first party import (`setup.cfg`):
```
[isort]
known_first_party = <my_package>
```

or telling tox to install the package in development mode (`tox.ini`):
```
[testenv]
usedevelop = true
```

**Comment by jbaublitz** [comment]
Thanks for the response. I'll see if any of the available options help here.
