### ISSUE TITLE
Comments are moved

### ISSUE THREAD

**Issue by Siecje** [timothycrosley/isort#1009]
Input 
```Python
import Blue.models as BlueModels
# comment for PlaidModel
from Plaid.models import PlaidModel
```

Output
```Python
# comment for PlaidModel
import Blue.models as BlueModels
from Plaid.models import PlaidModel
```

I would like the comment to be above `from Plaid.models import PlaidModel`.

**Comment by nickwilliams-eventbrite** [comment]
This is a duplicate of #726, reported over a year ago without even a response. :-(

**Comment by timothycrosley** [comment]
@nickwilliams-eventbrite To put this in perspective: I released isort to the world 6 years ago and have acted as the primary maintainer without pay since then (just 3 months ago tidelift has started to contribute $60 a month toward the project - which is awesome - but we all know the time value is much higher than that.) Still I have fixed most issues, and certainly I try to address all issues. But more importantly, I've been open to co-maintainers, and quick to accept pull requests. I'm sorry that you're issue was missed, it is no less important to me, but if it is extreamly important to you the best way to show that is with a pull-request.

**Comment by nickwilliams-eventbrite** [comment]
I apologize for airing my frustration so frankly. In the last year or so, I've submitted over a dozen PRs to various open source repos, and not a single one has been merged. Not because there was something wrong with them or I wouldn't respond to criticism ... I just can't get anyone to even acknowledge they've been posted. Participation in that manner is becoming more and more discouraging.

**Comment by nickwilliams-eventbrite** [comment]
Still ... this _is_ a duplicate and should probably be closed as such in favor of #726. :-)

**Comment by Siecje** [comment]
@timothycrosley Thank you for `isort`.

**Comment by timothycrosley** [comment]
@nickwilliams-eventbrite, No worries! If there's no movement on this by the community over the next few weeks I'll try to look into this. Unlike many project maintainers I make my highest priority getting pull-requests in, as I understand how frustrating it can be as a submitter to spend a lot of time working on something and never have it reviewed or merged in. This has been a great experience for me, as I've learned about so many new projects from this process (a submitter made me aware of pyproject.toml, and isort was one of the first tools to support it!). But, I understand not all, maybe not even most projects are operated this way - and how submitting PRs without response would be very disheartening. 

@Siecje, Thank you I appreciate that!
