### ISSUE TITLE
[question] Sorting by length seems to not be sorting by length after all?

### ISSUE THREAD

**Issue by kirk86** [timothycrosley/isort#1038]
Hi, thanks for the great package. I was wondering what is the behaviour when we sort by length?
For instance, I would like  to have my python file being sorted by length but it gives me the below behaviour
![image](https://user-images.githubusercontent.com/2902390/66749688-6ccc5380-ee82-11e9-88da-2272e970028c.png)

While I was expecting or want to have the import being sorted like this
![image](https://user-images.githubusercontent.com/2902390/66749732-853c6e00-ee82-11e9-889d-5d401909278b.png)

How can I achieve that? Isn't the `length-sort` option the one that should produce this behaviour?

**Comment by nickdimwill** [comment]
Intitial

```
import numpy as np
import sympy
import pandas as pd
import matplotlib.pyplot as plt
```

After `isort --length-sort <file>`

```
import numpy as np
import sympy
import pandas as pd
from matplotlib import pyplot as plt
```

**Comment by timothycrosley** [comment]
For clarification, isort is sorting by length, but it is not including the aliasing in that determination (numpy as np is seen as the same length as numpy). I'll work on improving length sort to include alias support before the next release

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make it's way in the 5.0.0 release:

https://github.com/timothycrosley/isort/pull/1152/files#diff-3e6dbf50f49313d010ff846279b07462R1123

Note that for best effect should be used with the force_sort_within_sections flag, that forces all smart logic off and only to base on lines. Such as in the above test.

Thanks!

~Timothy
