### ISSUE TITLE
isort doesn't work if non-import statement before imports?

### ISSUE THREAD

**Issue by dwhswenson** [timothycrosley/isort#1111]
(Using isort 4.3.21; Python 3.7.3; Mac OS 10.14.6)

Running `isort` has no effect on this file (`-d` option gives me the same text; `--diff` gives me no output):

```python
# isort_test.py
print("foo")
import os
```

However, add an import before the `print` statement:

```python
# isort_test2.py
import sys
print("foo")
import os
```

And it works as expected:

```
$ isort -d isort_test2.py
# isort_test2.py
import os
import sys

print("foo")
```

Is there a config somewhere that I'm missing? I would have expected the default behavior to be that `isort` would be able to move all imports to the top even if there are statements before the first import.

**Comment by timothycrosley** [comment]
Hi @dwhswenson,

Thanks for reporting this issue! isort is meant to be safe to run on large code bases. Occasionally, those large code bases do crazy things in code before imports, to change the behaviour of imports themselves. As a result isort tries to not have an opinion about these kind of things by *default* focusing only on what it is best at. However, I could definitely see value in making an optional flag that will collect all imports at the top of the file, before any code. For those with code bases that will allow it. As such, I'll leave this issue here to represent that work.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
I'm going to close this as isort has switched to a purely streaming approach to enable it to do such things as sort imports within functions. This means it will never move import blocks, just sort them where they are.
