### ISSUE TITLE
Spelling of first_party and third_party is inconsistent

### ISSUE THREAD

**Issue by vanschelven** [timothycrosley/isort#1139]
The spelling of the settings for first_party and third_party is inconsistent:

* `known_first_party`
* `import_heading_firstparty`

and similarly for `third_party` and `thirdparty`

**Comment by timothycrosley** [comment]
Hi @vanschelven,

Thanks for the report! While technically, spot-on, the reality is at this point usage of both are very engrained. And really, the inconsistency is small (and inconsistencies are fairly common of this nature in languages!). All this boils down to, in my estimation - the inconsistency is there, but the value to fix it is very small, and the cost very high. Either way having this issue here will be a good form of documentation.

Thanks!

~Timothy
