### ISSUE TITLE
Strange `typing_extensions` position

### ISSUE THREAD

**Issue by sobolevn** [timothycrosley/isort#1254]
Before `isort@5.0` my `typing_extension` imports were positioned in `3rd-party` section. Which, I guess, is the correct place for them.

Example:

```python
from typing import Generic

from typing_extensions import Final

from returns.hkt import Kind
```

After the update my code started to look like this:

```python
from typing import Generic

from returns.hkt import Kind
from typing_extensions import Final
```

It does not seem right to me.
Repo to try: https://github.com/dry-python/returns
Config: https://github.com/dry-python/returns/blob/master/setup.cfg

**Comment by timothycrosley** [comment]
@sobolevn isort 5.0.0 uses a new finding strategy that is guaranteed to be the same across environments, CI/CD etc. However, it is able to do this only by no longer taking env, requirements etc into the equation (see: https://github.com/timothycrosley/isort/issues/1147). I *think* you should get the behaviour you want on 5.0.0 simply by removing this line from your config: https://github.com/dry-python/returns/blob/master/setup.cfg#L74. otherwise, you can enable the old magical finding behaviour by enabling `--magic-placement`: https://timothycrosley.github.io/isort/docs/configuration/options/#old-finders

**Comment by sobolevn** [comment]
Yes, removing `default_section = FIRSTPARTY` solves my issue.
Thanks a lot for `isort` and quick help! 👍
