### ISSUE TITLE
Black profile not compatible with Black (ensure_newline_before_comments not working)

### ISSUE THREAD

**Issue by frenck** [timothycrosley/isort#1295]
Running isort 5.0.4 on the [Home Assistant](https://github.com/home-assistant/core) project with the following config:

```
[isort]
profile=black
indent = "    "
force_sort_within_sections = true
sections = FUTURE,STDLIB,INBETWEENS,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
default_section = THIRDPARTY
known_first_party = homeassistant,tests
forced_separate = tests
combine_as_imports = true
```

Example result from isort:

```py
from openzwave.group import ZWaveGroup
from openzwave.network import ZWaveNetwork
# pylint: disable=import-error
from openzwave.option import ZWaveOption
```

After running black:

```py
from openzwave.group import ZWaveGroup
from openzwave.network import ZWaveNetwork

# pylint: disable=import-error
from openzwave.option import ZWaveOption
```

It seems like the `ensure_newline_before_comments` from the Black profile is not being honored.

**Comment by timothycrosley** [comment]
Thank you for reporting! I'm sorry this issue impacted you!

This is fixed in isort 5.0.5 patch release.
It looks like the combination of `force_sort_within_sections` and `ensure_newline_before_comments` didn't yet have a test in place, so I've added an additional regression test to ensure this issue doesn't resurface.

Thanks!

~Timothy
