### ISSUE TITLE
Flake8 config cleanup

### ISSUE THREAD

**Issue by sztamas** [timothycrosley/isort#1350]
Is there a good reason to ignore `F401` globally in the project?

I got caught twice already by it, because I'm happy to have a successful `./scripts/done.sh` but when I create a PR DeepSource marks my PR as failed because of an unused import.

I tend to use no global ignores for flake8 (just set a max line length) and manually mark the exceptions with `# noqa: F401`, etc. 

Global ignores do save you the work to manually mark the exceptions but unfortunately as a side-effect mask all real problems as well.

**Comment by timothycrosley** [comment]
There was no reason other then time, I'd be happy to have the process improved! I do think some, if not all, the other ignores are intentional to deal with black / isort formatting incompatibilities. But identifying the ones that are necessary and the ones that aren't would also be helpful, and once complete the script could be commented to mention they are intentional and why

**Comment by sztamas** [comment]
Hi @timothycrosley,

This should be done now. See: https://github.com/timothycrosley/isort/pull/1351

Thanks,

Tamas
