### ISSUE TITLE
Change in isort result from 4 to 5

### ISSUE THREAD

**Issue by karrtikr** [timothycrosley/isort#1364]
In isort 5, it looks like imports are sorted in groups by default.

**Before**
```python
import rope.base.taskhandle
import rope.base.project


def test():
    pass

from rope.refactor.rename import Rename
from rope.refactor.extract import ExtractMethod, ExtractVariable

```

**After in isort 5**
```python
import rope.base.project
import rope.base.taskhandle


def test():
    pass

from rope.refactor.extract import ExtractMethod, ExtractVariable
from rope.refactor.rename import Rename

```

**After in isort 4**
```python
import rope.base.project
import rope.base.taskhandle
from rope.refactor.extract import ExtractMethod, ExtractVariable
from rope.refactor.rename import Rename


def test():
    pass

```

Just want to double check if it's expected, and what arguments can users use to restore the old behavior if they want? I am a bit concerned for our users who might find this unexpected.

**Comment by timothycrosley** [comment]
Hi @karrtikr,

This is indeed an intentional change as it makes isort much safer on code bases where side effects have to happen in-between import sections. However, the old style is still supported, I've added some additional information about this to the upgrade guide to help users who encounter it:

https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/#imports-no-longer-moved-to-top

Side-note: It would be really cool if somehow in VSCode, it was made available as a second right click / action so it could be done only when editing a file where you know you put an import into the middle.

Thanks!

~Timothy

**Comment by karrtikr** [comment]
Thanks for including additional info in the upgrade guide link!

> Side-note: It would be really cool if somehow in VSCode, it was made available as a second right click / action so it could be done only when editing a file where you know you put an import into the middle.

Maybe I misunderstood, but we already show it in the context menu. Users can click `Source action...`->`Sort imports`  or select `Sort imports` directly. Users can also run the command `Organize imports` or `Sort imports` from the command palette (`Ctrl+Shift+P`)

![image](https://user-images.githubusercontent.com/13199757/89098560-9f0d5a00-d39d-11ea-9a7f-f5c8b116e071.png)

**Comment by timothycrosley** [comment]
@karrtikr,

Yes I'm aware! And for the record I'm a huge fan of the integration, and the integration between Visual Studio Code and all Python tools, It has become my main editor because of it :).

![collect_imports](https://user-images.githubusercontent.com/2090154/89115749-a0dc2980-d440-11ea-8b66-e4567b2c1413.png)

I just had the thought pop in my head that adding a second command to move imports to the top, could be a nice way to integrate the new functionality. It could also make things to cluttered etc, but I thought I'd share the idea!

Thanks!

~Timothy

**Comment by karrtikr** [comment]
Cool, I'll pass on the idea. Actually we have been advised that our context menu is too long, so that's a concern. We can probably add that inside `Source Actions...`, and also create a command.
