### ISSUE TITLE
Tags on the default branch

### ISSUE THREAD

**Issue by hugovk** [timothycrosley/isort#1371]
I'm using isort with pre-commit, and use the `pre-commit autoupdate` command to update to the latest versions of isort and other tools.

However, it's not picking up today's 5.3.1 or 5.3.2. And strangely, if I manually set it to 5.3.2, `autoupate` resets it to 5.3.0.

This is because (https://github.com/pre-commit/pre-commit/issues/1555#issuecomment-670588288):

> yeah, isort doesn't tag their default branch or merge their tags into the default branch for some reason
> 
> `pre-commit autoupdate` picks the latest tag on the main branch

Would it be possible to tag the default branch, or merge the tags into it so the tools play nicely with each other?

It's great to see regular releases here, and thank you for all your work!

**Comment by timothycrosley** [comment]
Hi @hugovk, Thanks for pinging me! 

I've merged in the latest tags into the default branch so that `pre-commit` will pick them up. Precommit's behaviour of insisting on using the default branch (which is the one meant for PRs and therefore generally develop or unstable) is unintuitive for me, so I never guessed this would be a requirement! I'll make sure to include merging back into develop as a release checklist item from now on.

Thanks!

~Timothy

**Comment by hugovk** [comment]
Thank you, confirmed working as expected now! 👍
