### ISSUE TITLE
git+ syntax in requirements.txt breaks isort

### ISSUE THREAD

**Issue by danielgordon10** [timothycrosley/isort#1379]
If you have a line like 
`git+https://github.com/user/repo.git@hash`
in your requirements.txt file, isort will not parse it properly and will raise the error

```
It looks like a path. File 'git+https://github.com/user/repo.git@hash' does not exist.) during instantiation and cannot be used
RequirementsFinder encountered an error (Invalid requirement: 'git+https://github.com/user/repo.git@hash'```

Which rather than ignoring the single line it just stops isort from working entirely.

**Comment by timothycrosley** [comment]
What version of isort are you using? I ask because requirements.txt is a deprecated source to determine module placement. If you are the 5.0.0+ verson, unless you are asking to use this deprecated feature, it shouldn't error for you.

If you haven't yet moved to 5.0.0+, hopefully the upgrdade guide will be helpful:

https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/

**Comment by danielgordon10** [comment]
I was using v4. Cool to know this has been fixed in the newest version.
