### ISSUE TITLE
skip setting should take globs

### ISSUE THREAD

**Issue by stchris** [timothycrosley/isort#292]
I have a feature request: the "skip" setting should take glob expressions, to exclude multiple files at once. For instance `**/*_pb2.py`.

**Comment by dchanm** [comment]
I'm unsure the proper way to write tests, but I will write them with some guidance on what to do with the base64 blob.

The patch adds an additional settings flag -sg / --skip-glob which works similar to -s / --skip . It uses fnmatch to perform path globbing. 

Currently there are issues with backslash escapes and {} wildcards. A workaround for the former is to use [], e.g to match a literal \*, use [\*] instead of \\\* . The {} limitation is due to the settings splitting on commas.
