### ISSUE TITLE
User settings file ignored if project's settings exists

### ISSUE THREAD

**Issue by ziima** [timothycrosley/isort#331]
The priority of settings file is described in [wiki](../wiki/isort-Settings). But I found this order is not followed in the code. If case project contains `.isort.cfg` file (e.g. project specific settings) and user has it's own `~/.isort.cfg` (e.g. user preferences etc.), the project file is loaded, but the user's config file is ignored. I wouldn't expect this behaviour based on documentation.

**Comment by apinkney97** [comment]
The code in question looks like
```python
def from_path(path):
    computed_settings = default.copy()
    _update_settings_with_config(path, '.editorconfig', '~/.editorconfig', ('*', '*.py', '**.py'), computed_settings)
    _update_settings_with_config(path, '.isort.cfg', '~/.isort.cfg', ('settings', 'isort'), computed_settings)
    _update_settings_with_config(path, 'setup.cfg', None, ('isort', ), computed_settings)
    return computed_settings


def _update_settings_with_config(path, name, default, sections, computed_settings):
    editor_config_file = default and os.path.expanduser(default)
    tries = 0
    current_directory = path
    while current_directory and tries < MAX_CONFIG_SEARCH_DEPTH:
        potential_path = os.path.join(current_directory, native_str(name))
        if os.path.exists(potential_path):
            editor_config_file = potential_path
            break

        new_directory = os.path.split(current_directory)[0]
        if current_directory == new_directory:
            break
        current_directory = new_directory
        tries += 1

    if editor_config_file and os.path.exists(editor_config_file):
        _update_with_config_file(editor_config_file, sections, computed_settings)
```
which to me looks like we start with a copy of the default settings, then these are updated with, in order
* The first encountered file called `.editorconfig` up to `MAX_CONFIG_SEARCH_DEPTH` levels up
 * or if no `.editorconfig` file exists, `~/.editorconfig`
* The first encountered file called `.isort.cfg` up to `MAX_CONFIG_SEARCH_DEPTH` levels up
 * or if no `.isort.cfg` file exists, `~/.isort.cfg`
* The first encountered file called `setup.cfg` up to `MAX_CONFIG_SEARCH_DEPTH` levels up
 * or if no `setup.cfg` file exists, `~/setup.cfg`

I'd find it more convenient if the order was
* Default settings
* `~/x.cfg`
* *All* encountered files with name `x.cfg` up to `MAX_CONFIG_SEARCH_DEPTH` levels above, with nearest files having precedence

where `x.cfg` is each of the three config file name variants.

This way we can stack configs. I use a custom section for "things in this package" that comes between FIRSTPARTY and LOCALFOLDER, ie
```
sections=FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,THISPACKAGE,LOCALFOLDER                                                                             
known_thispackage=mypackagename
```
and it would be nice to have just `known_thispackage` in the config of the root of package, with the remainder of the config in a file in a higher directory.

**Comment by ziima** [comment]
+1

**Comment by shanx** [comment]
With the current machinery in place, a project that defines its own local isort.cfg cannot assume any default. It must define each settings locally with the default value for it to ensure that all these default values will be in place after isort is done merging settings from different config files using its `_update_settings_with_config` logic.

As an example I was working on https://github.com/YPlan/django-perf-rec/pull/69. They defined a local isort.cfg, wanting to use the default sections available to isort they left the sections empty. Unfortunately my `~/.isort.cfg` did define sections. So running their linter started complaining about  imports in the project, because for the sections part it used my `~/.isort.cfg`. The only remedy currently for any project would be to overrule each setting within their isort config using the default values.

Since isort is used by so many we can not change this behaviour. I would suggest though to add a commandline argument `--no-merge-settings` which makes isort only find the first isort settings file and merges these with the defaults.

**Comment by timothycrosley** [comment]
isort is chaning the way config's work to match that of other formatters (such as black) which will mean no longer supporting any config merging. This is intentional and will take effect on the 5.0.0 release. It means some duplication may be necessary in some cases, but solves a wide range of errors that stem from unexpected config merging.

Thanks!

~Timothy
