### ISSUE TITLE
Single, too-long imports with Vertical Hanging Indent

### ISSUE THREAD

**Issue by mknecht** [timothycrosley/isort#365]
If I have a single import that exceeds line_length, isort will use the backslash to enforce the line-length. This feels wrong, as we've configured “Vertical Hanging Indent” for multi-lines.

We get:

```
from blub import /
    veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylongname
```

where we'd rather have

```
from blub import (
    veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylongname,
)
```

(We get this behavior correctly for long lines.)

Apart from being consistent, it'd also clarify and minimize the diff when a new import is added.
Finally, we'd like to adhere to PEP8:

    “The preferred way of wrapping long lines is by using Python's implied line continuation
    inside parentheses, brackets and braces. Long lines can be broken over multiple lines
    by wrapping expressions in parentheses. These should be used in preference to using
    a backslash for line continuation.”

Kudos to @dashmug for being a nit-picker.

**Comment by timothycrosley** [comment]
I'll do my best to fix this issue, I agree with the sentiment

Thanks!

~Timothy

**Comment by bootandy** [comment]
https://github.com/timothycrosley/isort/blob/develop/isort/isort.py#L418

It looks like we just change the integer from 1 to 0 here ^

but doing so breaks 6 tests

because outputs that used to look like this: [wrap is due to low line length setting]

```
from translate.storage.placeables import \n
    general
```
Start to use the default Wrap mode and get turned into this.
`from translate.storage.placeables import (general)
`

Although I'd argue that the above should be this instead 

`from translate.storage.placeables import (
    general
)
`

I think we are pulling at a thread and things could unravel here.

**Comment by mknecht** [comment]
Maybe a config option --len-from-imports-greater-than ? ;)

(Can't think of a good name, because my mind hasn't familiarity with all the config options and their implications.)

**Comment by timothycrosley** [comment]
A Fix for this has been implemented by @bootandy and merged into develop, ready to make it into the next release :)
