### ISSUE TITLE
Single-letter classes not sorted correctly

### ISSUE THREAD

**Issue by blueyed** [timothycrosley/isort#376]
It seems like imported classes with a length of 1 will be considered to be constants and sorted before other classes:

```
-from django.db.models.expressions import Case, F, When
+from django.db.models.expressions import F, Case, When
```

This is triggered controlled by the `'order_by_type'` setting and happens in https://github.com/timothycrosley/isort/blob/2efc438c1934032e802745c0cf4666cfd7d53e81/isort/isort.py#L274-L280.

**Comment by dwaynebailey** [comment]
I hit this with Django's `Q` class.  @blueyed I was wondering if a better solution would be to allow users to define exceptions?  They could very well have a case where a single uppercase is a constant.

**Comment by timothycrosley** [comment]
@dwaynebailey, I think you have the right idea. There really isn't another good way to do it, since actually looking into the module to determine what type an element is would be super-inefficient, and break 2 of isorts goals (to work independent of the implementation the Python code was written for, and to run quickly over a large code base). Honestly, one letter names for *anything* is generally bad practice, of-course you can't help the fact Django uses them - so a list of exceptions that you can add to the config would be a good idea here.

Thanks for raising this issue @blueyed!

~Timothy
