### ISSUE TITLE
Skips files provided as filename

### ISSUE THREAD

**Issue by kayhayen** [timothycrosley/isort#412]
```
isort -ns nuitka/__init__.py nuitka/__init__.py 
Skipped 1 files
```

I am using "find" to avoid isort to go into inline copies. I probably need not do it. I found it strange though that the "__init__.py" file gets skipped even if provided as a filename, and even if I told it to not skip that. Something wrong there?

Yours,
Kay

**Comment by timothycrosley** [comment]
Hi @kayhayen, can you try:

`isort -ns __init__.py nuitka/__init__.py` ?

isort by default in 4.x.x skips `__init__.py` as that's often a file with such special importing orders due to avoidance of circular references as to be difficult to apply general rules to. This is the only file name isort skips by default. However, the way -ns works in isort is to not apply skips rules that are in not skip. Because of this the rule name must match exactly, in 5.0.0 I hope to make this smarter to enable use cases like suggested but it's not there yet.

I hope this is helpful,

Thanks!

~Timothy

**Comment by kayhayen** [comment]
Hello,

thanks for the quick response, and the great tool. :-)

2016-03-29 22:14 GMT+02:00 Timothy Edmund Crosley <notifications@github.com>
:

> Hi @kayhayen <https://github.com/kayhayen>, can you try:
>
> isort -ns __init__.py nuitka/__init__.py ?
>
That works as intended. It wasn't obvious to me though that such a rule
existed. Maybe include the rule name in the "Skipped 1 file" message.

> isort by default in 4.x.x skips __init__.py as that's often a file with
> such special importing orders due to avoidance of circular references as to
> be difficult to apply general rules to. This is the only file name isort
> skips by default. However, the way -ns works in isort is to not apply skips
> rules that are in not skip. Because of this the rule name must match
> exactly, in 5.0.0 I hope to make this smarter to enable use cases like
> suggested but it's not there yet.
>
> I hope this is helpful,
>
I am using "isort:skip" annotations for cases where this is true. It's
never true for the packages, but e.g. for my main binary, where I re-fork
it, and want to avoid doing little more than command line parsing
sufficient to decide if that's needed.

What this gave me (apparently the ancient pip installed isort that I had
used did it too, just never said so), was at least file end new line
corrections in one case. Because getting that right is also a welcome
feature of isort.

I will try the new (to me) project mode and see if I can get it to properly
skip the code that I want to get skipped too. I also noticed that check
mode, something I will gladly use on my Buildbot soonish.

Yours,
Kay
