### ISSUE TITLE
4.2.7 preparations merged, missing 4.2.6 tag

### ISSUE THREAD

**Issue by sandrobonazzola** [timothycrosley/isort#474]

**Comment by sandrobonazzola** [comment]
Also missing pypi release https://pypi.python.org/pypi/isort

**Comment by sandrobonazzola** [comment]
missing tag and pypi release caused Fedora packaging to not pick up the new release: http://koji.fedoraproject.org/koji/packageinfo?packageID=22885

**Comment by timothycrosley** [comment]
So sorry about this! I'm not sure exactly what happened, most likely these where place holder version numbers for what would be released, once a release happened, since even the code still had it at 4.2.5. In any case I've just released 4.2.8 which is correctly tagged and pushed to PYPI, and rolled in all changes from 4.2.6 & 4.2.7 into it.

Thanks!

~Timothy
