### ISSUE TITLE
Inconsistent behaviour in python2/python3

### ISSUE THREAD

**Issue by mapleoin** [timothycrosley/isort#479]
Running the same version of isort (4.2.5) in python2 and python3, I get different behaviour:

```
(python2) $ isort caca.py 
(python2) $ cat caca.py 
from workalendar.europe import UnitedKingdom

from future.standard_library import hooks
(python3) $ isort caca.py
(python3) $ cat caca.py
from future.standard_library import hooks
from workalendar.europe import UnitedKingdom
```

**Comment by timothycrosley** [comment]
https://github.com/timothycrosley/isort/pull/534/files added a test to verify this isn't an inherit isort issue, but probably has something to do with your specific environment set up

**Comment by gagern** [comment]
Running the example on my system (i.e. without tox or virtualenv) I see the version *with* the newline for both Python 2 and Python 3. That's presumably because I have [a package called future](http://python-future.org/) installed for both versions, so the first line gets classified as `THIRDPARTY` while the second is `FIRSTPARTY`. Which means that test breaks for me, and I find it slightly annoying if I can't test things without tox any more. With tox everything is fine, though.

**Comment by blueyed** [comment]
@gagern 
See https://github.com/timothycrosley/isort/pull/861.
