### ISSUE TITLE
multiprocess execution a-la 'autopep8 -j'

### ISSUE THREAD

**Issue by glyph** [timothycrosley/isort#522]
`autopep8 -j -1` nearly tripled the speed of autopep8's execution across my codebase. Sadly there does not seem to be an equivalent option for `isort`.  It would be cool if there were!

**Comment by timothycrosley** [comment]
Very cool idea! I agree this could def be useful, and shouldn't actually be too difficult to implement. 5.0.0 would be a good target for this, I'm focusing on bug fixes right now, so If someone else wants to take a stab at it (including you) I would enthusiastically review and presumably accept any pull requests, otherwise after bugs are resolved I'll revisit this.

Thanks for the great suggestion!

~Timothy

**Comment by timothycrosley** [comment]
isort now supports the `-j` flag! 

Thanks!

~Timothy
