### ISSUE TITLE
release 4.2.11 broken

### ISSUE THREAD

**Issue by saily** [timothycrosley/isort#549]
`4.2.9` works fine, but the latest release `4.2.11` raises following exception:

    Traceback (most recent call last):
      File "/dev/my_project/bin/isort", line 7, in <module>
        from isort.main import main
      File "/dev/my_project/lib/python3.4/site-packages/isort/__init__.py", line 26, in <module>
        from .isort import SortImports
      File "/dev/my_project/lib/python3.4/site-packages/isort/isort.py", line 43, in <module>
        from .pie_slice import OrderedDict, OrderedSet, input, itemsview
    ImportError: cannot import name 'input'

I'm running Python 3.4.5

**Comment by saily** [comment]
duplicate #548

**Comment by saily** [comment]
@timothycrosley how could your tests pass here?

**Comment by timothycrosley** [comment]
Somehow the wheel file had an outdated version of pie_slice, while the source version had the correct one, I've pushed out 4.2.12, after removing all cached build files, and verified it has the correct version of the file, can you try again? The reason the test would pass, is only because the source code is correct - but somehow the wheel creation used an incorrect version of the source file, even though it's created at the same time as the sourced zip.

Thanks!

~Timothy
