### ISSUE TITLE
Isort is not compatible with flake8

### ISSUE THREAD

**Issue by normanjaeckel** [timothycrosley/isort#550]
Running `isort --check-only` on this code fails:

```python
import sys


# Some classes

class One:
    pass


class Two:
    pass


# Some other stuff

def foo():
    print(sys.path)
```

But if I remove one blank line before the first comment as isort wants me to do, flake8 (v3.3.0) fails. I think isort produces the wrong output because it ignores the comment and counts to next blank line. flake8 is correct I think.

**Comment by timothycrosley** [comment]
This is intentional, as far as I'm aware isort is correct:

see: https://github.com/timothycrosley/isort/issues/435

In pep8 you are only supposed to have 2 lines between class and definitions and function definitions. Since the comment is floating and not clearly associated with a class it correctly should only have one new line.

Thanks!

~Timothy

**Comment by normanjaeckel** [comment]
See https://gitlab.com/pycqa/flake8/issues/336

**Comment by edmorley** [comment]
From the discussion in PyCQA/pycodestyle#652, it seems that the PEP8 spec actually allows both cases, so perhaps isort should allow this?

**Comment by sigmavirus24** [comment]
@edmorley specifically, it allows two blank lines after imports before a comment or anything else. It doesn't say "there may only be one blank line after imports unless a class definition follows immediately" which is functionally what isort seems to be doing. Perhaps this behaviour should be optional to the user.

**Comment by timothycrosley** [comment]
isort, when in code modification must make a choice. It already has options to allow you to change this choice (IE force 2 lines after imports), but defaults to the implied pep8 (one line between import statements, 2 if followed by a function or class definition). isort the checker allows ignoring whitespace differences entirely. I really thing the only reason this comes up though, is because the current bug in pycodestyle encourages the following of this pattern:

'''python

import os

# comment

class X():
   pass
```

Which we both agree is invalid.

Thanks!

~Timothy
