### ISSUE TITLE
Incorrect sorting, this is no longer considered stdlib?

### ISSUE THREAD

**Issue by meetmangukiya** [timothycrosley/isort#559]
```
import curses
import this
```

is sorted as 
```
import curses

import this
```

In isort 4.1 it is left as it is, the bug was introduced in this release.

**Comment by meetmangukiya** [comment]
strange because 
```
import curses
import io
```

is left as is without sorting it buggily

**Comment by timothycrosley** [comment]
This is presumably because `this` is not listed as a standard lib module here: https://docs.python.org/3/py-modindex.html - as a result of it being an easter egg feature. I've updated isort's known_standard_library list to include it and pushed to develop, so it will make it into the next release.

Thanks!

~Timothy
