### ISSUE TITLE
Add more verbose explanation for diff option

### ISSUE THREAD

**Issue by bendikro** [timothycrosley/isort#593]
After upgrading isort version, it now wants to insert an empty line between two first-party modules. It would be useful to be able to get an explanation on why it wants to do this.

**Comment by timothycrosley** [comment]
I agree this kind of explanation would be useful. However, due to the indended operation of isort, it is more difficult to add then the use I think it provides. This is because isort is a formatter, not a linter. It formats code a certain way, based on rules etc, but the linting happens only as a diff. Since the linting wasn't built as an intention from the beginning, post determing the cause becomes very difficult, beyon the truth: the diff between the unformatted and formatted code exists.
