### ISSUE TITLE
'check' in setup.cfg not functioning?

### ISSUE THREAD

**Issue by whw** [timothycrosley/isort#599]
Hi,

I've been trying to move a configuration over from the command line options specified here:
`isort --check-only --diff --multi-line 3 --verbose --recursive --line-width 79`

into this `setup.cfg` configuration:
```
[isort]
check = True
show_diff = True
multi_line_output = 3
recursive = True
verbose = True
line_length = 79
```

Everything seems to have parity except for `check` vs `--check-only`. Using `--check-only` will result in errors (such as line length) being printed, while setting `check = True` does not.

isort version: 4.2.15
python version: 2.7.6

**Comment by timothycrosley** [comment]
check only is a command line only flag, and you are correct that it doesn't have any impact from the settings file. This however is intentional because settings file are to define how imports should be sorted and formatted, and the check only flag only defines how the command line interacts with the results of formatting.

Thanks!

~Timothy

**Comment by whw** [comment]
Thanks!
