### ISSUE TITLE
Include information about which files are skipped

### ISSUE THREAD

**Issue by rogpeppe** [timothycrosley/isort#614]
When I run isort on a directory it says: "Skipped 5 files" but there's no indication of which files have been skipped or why. It would be good if isort could print that information too.

**Comment by exhuma** [comment]
To see which files have been skipped, you can add the `-vb` flag (note the single dash). It will *not* show you *why* the files have been skipped though!

**Comment by samestep** [comment]
> To see which files have been skipped, you can add the `-vb` flag (note the single dash). It will _not_ show you _why_ the files have been skipped though!

@exhuma In `isort` version 5.7.0 that gives the following error:
```
isort: error: argument -b/--builtin: expected one argument
```

**Comment by exhuma** [comment]
Thanks @samestep for the update. I edited my earlier response to reflect that.

**Comment by pothitos** [comment]
Hello! I ran the 5.8.0 version with the `-v` argument and seems to explain why it skipped one file.

```
/usr/local/lib/python3.9/site-packages/isort/main.py:1181: UserWarning: .git was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
  warn(
Skipped 1 files
```

**Comment by timothycrosley** [comment]
@exhuma / others, sorry I missed the call to reopen this! @pothitos is correct that it now shows **why** it is skipped. I think the problem here is just that isort with the 5.0.0 released some flags, including -vb -> -v (as @pothitos mentioned, thank you!), as a general note - I tend to miss updates to closed tickets since they only show up in my email (which is fairly overcrowded) so the best option sometimes is to just open a new ticket so I see it!

**Comment by Barmaley0** [comment]
> > Чтобы увидеть, какие файлы были пропущены, вы можете добавить флаг `-vb`(обратите внимание на одинарное тире). Однако он _не_ покажет вам _, почему_ файлы были пропущены!
> 
> @exhumaВ `isort`версии 5.7.0 выдает следующую ошибку:
> 
> ```
> isort: error: argument -b/--builtin: expected one argument
> ```

Hello. Have you found a solution?
