### ISSUE TITLE
Logic changes in 4.3?

### ISSUE THREAD

**Issue by ThiefMaster** [timothycrosley/isort#653]
After updating to 4.3 and running isort on my codebase, I get these changes which were not applied previously with 4.3.15.

- The JSONB change looks good, I'm surprised the old order was valid before.
- I'm not sure why the RoleConverter import was moved up. `R>P` and I guess it should use the name in the imported module. not the local alias?
- I don't understand why my datetime import gets split. 
- The flask import change looks good. I guess it was doing a case-sensitive check previously?

```diff
--- /home/adrian/dev/indico/src/indico/modules/events/models/static_list_links.py:before        2018-01-29 13:50:57.845604
+++ /home/adrian/dev/indico/src/indico/modules/events/models/static_list_links.py:after 2018-02-01 11:25:39.620275
@@ -18,8 +18,8 @@

 from uuid import UUID, uuid4

+from sqlalchemy.dialects.postgresql import JSONB
 from sqlalchemy.dialects.postgresql import UUID as pg_UUID
-from sqlalchemy.dialects.postgresql import JSONB

 from indico.core.db import db
 from indico.core.db.sqlalchemy import UTCDateTime
--- /home/adrian/dev/indico/src/indico/modules/events/papers/fields.py:before   2018-01-29 13:50:57.847604
+++ /home/adrian/dev/indico/src/indico/modules/events/papers/fields.py:after    2018-02-01 11:25:39.863155
@@ -18,8 +18,8 @@

 import json

+from indico.modules.events.papers.settings import RoleConverter
 from indico.modules.events.papers.settings import paper_reviewing_settings as settings
-from indico.modules.events.papers.settings import RoleConverter
 from indico.web.forms.fields import JSONField
 from indico.web.forms.widgets import JinjaWidget

--- /home/adrian/dev/indico/src/indico/util/date_time.py:before 2018-01-29 13:50:57.899603
+++ /home/adrian/dev/indico/src/indico/util/date_time.py:after  2018-02-01 11:25:44.195697
@@ -15,8 +15,9 @@
 # along with Indico; if not, see <http://www.gnu.org/licenses/>.

 from collections import OrderedDict
+from datetime import datetime
 from datetime import time as dt_time
-from datetime import datetime, timedelta
+from datetime import timedelta

 import pytz
 from babel.dates import format_date as _format_date
--- /home/adrian/dev/indico/src/indico/web/flask/util.py:before 2018-01-29 13:50:57.907603
+++ /home/adrian/dev/indico/src/indico/web/flask/util.py:after  2018-02-01 11:25:44.987706
@@ -21,9 +21,9 @@
 import time
 from importlib import import_module

+from flask import Blueprint, current_app, g, redirect, request
 from flask import send_file as _send_file
 from flask import url_for as _url_for
-from flask import Blueprint, current_app, g, redirect, request
 from flask.helpers import get_root_path
 from werkzeug.datastructures import FileStorage, Headers
 from werkzeug.exceptions import NotFound
```

My .isort.cfg:

```
[isort]
line_length=120
multi_line_output=0
lines_after_imports=2
sections=FUTURE,STDLIB,THIRDPARTY,INDICO,FIRSTPARTY,LOCALFOLDER
known_third_party=flask_multipass,flask_pluginengine
known_indico=indico
skip_glob=20??????????_*_*.py
not_skip=__init__.py
```

**Comment by edmorley** [comment]
Yeah we're seeing similar:
https://travis-ci.org/mozilla/treeherder/jobs/335981459#L610

**Comment by Plazmaz** [comment]
Also seeing this.

**Comment by markdoliner** [comment]
Regarding the change in sort order for "from foo import bar *as baz*," it looks like this was intentional. Relevant comments: https://github.com/timothycrosley/isort/issues/590#issuecomment-325569627

The new way seems mildly better to me.

Seems worth mentioning in the 4.3.0 change list at https://github.com/timothycrosley/isort/blob/develop/CHANGELOG.md

**Comment by timothycrosley** [comment]
@markdoliner is correct that this is intentional, and I believe correct behaviour. It was my mistake to miss this change when putting together the changelog, and I've now updated to reflect. Let me know if having the old behaviour is important to any of you, now that you have the reasoning behind the change, and I can work on reinstating it as a configuration flag.

Thank you, and sorry for any confusion this caused!

~Timothy

**Comment by ThiefMaster** [comment]
I think having a setting to control whether to split imports as soon as `as` is used would be useful.

I'm still not sure about this part though:

```diff
+from indico.modules.events.papers.settings import RoleConverter
 from indico.modules.events.papers.settings import paper_reviewing_settings as settings
-from indico.modules.events.papers.settings import RoleConverter
```

It looks like it's sorting by the name used to make the imported object available in the module (`settings`), and not by the source name (`paper_...`). I think this should be configurable as well - since nicely sorted imports are mainly to make it easier for humans to read it, and humans typically read from left to right, it's strange that the alias name is used for sorting...

**Comment by markdoliner** [comment]
> It looks like it's sorting by the name used to make the imported object available in the module (settings), and not by the source name (paper_...)

@ThiefMaster FYI I believe it _does_ sort by the source name (`paper_...`). I think the reason you're seeing this change is because it sorts all capital letters above all small letters.

> Let me know if having the old behaviour is important to any of you

The old behavior is not important for me. For my use case we mostly just want the imports to be sorted consistently for all our developers. The actual sort order is less important (though I do think the new behavior is more logical).

**Comment by nickwilliams-eventbrite** [comment]
There should really be a setting to control this:

>it sorts all capital letters above all small letters.

We came to an organizational decision to ignore case completely in the ordering of imports, and we have no way to configure isort to enforce this. It's specifically doing the opposite without a way to say otherwise.
