### ISSUE TITLE
Ability to setup `virtual_env` relative to `.isort.cfg` location

### ISSUE THREAD

**Issue by prokher** [timothycrosley/isort#659]
In our setup it is necessary to specify a location of a virtual environment relative to `.isort.cfg` file, but I cannot find the way to do it. It is obvious why I cannot use absolute path in `.isort.cfg` - this file lives in the repository. But when I specify relative path it treats it relative to the current working directory. So I simply cannot run `isort` from any directory except the root of the project, cause if I do so `isort` cannot find the virtual env and starts treating third party libraries as a first party ones.

**Comment by timothycrosley** [comment]
This is no longer needed as isort now longer cares about venv. How ever I think in spirit this is now implemented in 5.0.0 as isort will use your projects root directory to determine local source files, and it uses .isort.cfg to automatcially determine that when present.

**Comment by prokher** [comment]
Dear @timothycrosley, well, I've tried latest versions and now simply cannot understand how to convince `isort` to consider thirdparty libraries in the `{project_dir}/.venv` as `THIRDPARTY`. It considers it as `FIRSTPARTY` which brakes the order of import 🤔. Can you please describe how to achieve this? In previous versions I could do at least something, but now... well, it looks like a regression.

**Comment by timothycrosley** [comment]
@prokher, can you provide the output of `--show-config`? isort 5 changed how finding works completely, so things default to THIRD_PARTY unless specified otherwise in the configuration, see: https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/#module-placement-changes-known_third_party-known_first_party-default_section-etc and https://github.com/timothycrosley/isort/issues/1147. Most likely, you can simply remove a lot of configuration options you used to have to setup for isort to place modules correctly, and things will "Just Work.". Either way I'm happy to help guide you through the process, and If you run into any issues I would like to know so I can update the core project and fix them.

Here's an example of the issue being worked through with another user, in case the solution to your case is contained within there as well: https://github.com/timothycrosley/isort/issues/1336

Thanks!

~Timothy

**Comment by prokher** [comment]
@timothycrosley, indeed, I just removed old configuration and it seems to work fine. Thank you for great work!
