### ISSUE TITLE
Support paths which are known to be in a particular section

### ISSUE THREAD

**Issue by benjaminjkraft** [timothycrosley/isort#692]
isort currently supports specifying that a particular module is known to belong in a particular section.  But it would be great for us to be able to do the same for a particular path-prefix.  That is, if we do
```python
sys.path.insert(0, 'third_party')
import module1  # third_party/module1.py
import module2  # third_party/module2.py
```
currently we'd have to say `known_third_party=module1,module2` to get the right behavior; it would be great if instead we could say instead `known_third_party_paths=third_party`.  This would match how virtualenv directories are [currently handled](https://github.com/timothycrosley/isort/blob/2071da8/isort/isort.py#L287).

**Comment by lundberg** [comment]
We have kind of the same problem. Normally we have a `src` folder in the repo-root containing top-level packages/apps. To treat all packages in `src` we have to manually add them in `setup.cfg`.

I made a quick extension of the pattern-handling so that paths can be given along with modules when defining the known patterns, i.e. `isort -p src/ ...`

Does this solves your issues as well @benjaminjkraft?

**Comment by benjaminjkraft** [comment]
If I'm understanding you correctly, yeah, that's more or less equivalent.  I don't know if there's a desire to implement it as a separate option for compatibility; either way would work for us.

**Comment by lundberg** [comment]
Since the patterns themselves, while iterated, gets identified as paths and expanded to a list of sub packages, i don't think there should be any compatibility issues. One can mix modules (standard patterns) and paths.

i.e. `isort -p foo,bar,baz/,ham,spam/`

*baz/* and *spam/* gets expanded and added to *foo, bar and ham*

**Comment by lundberg** [comment]
@timothycrosley should I add a config option to enable this path identification for clarity, like `expand_known_paths`?

Performance should anyhow be equal effort to check the setting or if the pattern ends with a `/`.
