### ISSUE TITLE
isort should support alphabetical-only sorting

### ISSUE THREAD

**Issue by OddBloke** [timothycrosley/isort#699]
I have some codebases where the naming conventions don't follow the expected constant/class/function naming patterns, so isort interleaves the imports weirdly when it tries to guess the type of an imported name based on its capitalisation.

I would like to be able to (optionally) tell isort to do a pure alpha-sort.

**Comment by timothycrosley** [comment]
Hi @OddBloke,

isort has a couple of options to enable what you want:

order_by_type: False <- This will tell isort not to care about the types of imports
force_alphabetical_sort: True <- forces all imports to be sorted as a single section, instead of within other groups (such as straight vs from

Thanks!

~Timothy

**Comment by OddBloke** [comment]
Thanks!
