### ISSUE TITLE
'user' is not a Python3 package

### ISSUE THREAD

**Issue by camilonova** [timothycrosley/isort#778]
In Python2 'user' was a package, but not anymore in Python3.

Seems you are using it as a python package:
https://github.com/timothycrosley/isort/blob/develop/isort/settings.py#L99

It is somehow related to: https://github.com/PyCQA/pylint/issues/2532

Thank you.

**Comment by camilonova** [comment]
@jdufresne Hi there. Can you take a look into it?

**Comment by istommao** [comment]
I have the same error

**Comment by camilonova** [comment]
@timothycrosley can you? This is just really annoying and seems to be a quick fix.

**Comment by istommao** [comment]
@timothycrosley
I agree with @camilonova. pylint use isort, the inspect really annoying!

**Comment by hugovk** [comment]
What is the quick fix?

`user` cannot be removed from the list because the [README](https://github.com/timothycrosley/isort/blob/develop/README.rst) says isort:

> requires Python 3.4+ to run but supports formatting Python 2 code too.

Does isort know which Python versions it is _targetting_? (Not the version it is running on.)

If it does, we could split `known_standard_library` into three:

* `known_standard_library`
* `known_standard_py2_library`
* `known_standard_py3_library`

And then join together the lists for targetted versions. (This could be more nuanced, for libraries added and removed between 3.x minor versions.)

But I don't think isort knows or makes any assumptions which versions are targetted. Should that be added?

For comparison, Black has a  `--target-version` option which defaults to detecting on a per-file basis: https://github.com/ambv/black#command-line-options

**Comment by timothycrosley** [comment]
I think the only fix for this is the --target-version.  @hugovk is mentioning, it is not quick, but shouldn't be too difficult either.

Thanks!

~Timothy

**Comment by camilonova** [comment]
Python 3.4 should hit EOL in a few days https://devguide.python.org/#branchstatus

Removing it should be the quick fix, right?

You can see also https://github.com/IATI/pyIATI/issues/300#issue-306499974

**Comment by timothycrosley** [comment]
@camilonova 

touche.

My concern wasn't about Python3, but Python2.7 which isort will support till at least it's EOL, however looking at it more:

https://docs.python.org/2/library/user.html?highlight=user#module-user

on the 2 side its: 

Deprecated since version 2.6: The user module has been removed in Python 3.

I'll make a release to remove `user`.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
The removal of `user` has been moved into the develop branch. I plan on making a release on or shortly after Python3.4's end of life that includes this change.

Thanks!

~Timothy
