### ISSUE TITLE
Imports sort priority is different depending if package is already installed

### ISSUE THREAD

**Issue by richardlthomas** [timothycrosley/isort#844]
When testing issue 679, it was found that imports appear to be sorted differently if the corresponding package is already installed vs. if it isn't/is not a real package.

```
       test_input = ('import os\n'
                      '\n'
                      'import requests\n'
                      'import zed # NOQA\n'
                      'import ujson # NOQA\n'
                      '\n'
                      'import foo')
        test_output = ('import os\n'
                       '\n'
                       'import foo\n'
                       'import requests\n'
                       '\n'
                       'import zed # NOQA\n'
                       'import ujson # NOQA\n')
>       assert SortImports(file_contents=test_input).output == test_output
E       AssertionError: assert 'import os\n\...json # NOQA\n' == 'import os\n\n...json # NOQA\n'
E           import os
E           
E         + import foo
E           import requests
E         - 
E         - import foo
E           ...
```

**Comment by blueyed** [comment]
Just for reference: https://github.com/timothycrosley/isort/issues/679

Isn't this expected in general?  (first party vs. third party)

**Comment by timothycrosley** [comment]
I think that's correct. I do think this issue highlights that there is some errors and confusion caused by the fact that isort uses some environmental traits to decide where to align imports, that leads to different behaviour depending on whether you have a virtual enviornment active or not etc - that should be improved to improve the usefulness and consistency in a CI setting. 

Thanks!

~Timothy
