### ISSUE TITLE
Python 3.4 and pip 19.0.3 fails to install isort 4.3.9

### ISSUE THREAD

**Issue by imbaczek** [timothycrosley/isort#849]
```
Complete output from command python setup.py egg_info:
/usr/local/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
warnings.warn(msg)
error in isort setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

python 3.4
pip 19.0.3

**Comment by tomaxsas** [comment]
python 2.7 also fails...

**Comment by mkurnikov** [comment]
I can only reproduce with setuptools==12.0.5 (got idea from https://github.com/jazzband/django-axes/issues/349#issuecomment-433215726). Please, update your setuptools to version 20+ (https://stackoverflow.com/questions/21082091/install-requires-based-on-python-version/32643122#32643122).

**Comment by susam** [comment]
Filed a related issue at #853. The `install_requires` parameter in the [`setup()` call](https://github.com/timothycrosley/isort/blob/4.3.9/setup.py#L30) was removed from release 4.3.7 but it has come back in release 4.3.9 which is one of the factors triggering this issue. In issue #853, I have asked if this `install_requires` parameter was brought back intentionally in 4.3.9.

By the way, we have a different but similar build failure in cloudmarker/cloudmarker#45 due to an old version of `setuptools`, i.e., `setuptools 35.0.2`, in Travis CI build environment for Python 3.4. The issue does not occur with `setuptools 36.2.0` and later versions. Therefore the issue does not occur in `setuptools 40.0.0` and `setuptools 38.2.4` in Travis CI build environments for Python 3.5 and Python 3.6, respectively.

**Comment by timothycrosley** [comment]
Unless I get strong feedback otherwise, I'm going to keep this as invalid and simply require everyone to update their setuptools version - simply because it is not possible to list these optional requirements in a consistent way otherwise when dealing with wheel distribution AFAIK.
@susam, 4.3.7 & 4.3.8 also included the syntax in question, the tags were simply created incorrectly due to a typo on my part. I've updated the tags to be accurate.

Thanks everyone!

~Timothy
