### ISSUE TITLE
--skip doesn't seem to do anything anymore

### ISSUE THREAD

**Issue by gaffney** [timothycrosley/isort#920]
Hello,

Around a month or two ago `isort` started ignoring all the items listed under `skip` in my `.isort.cfg`. I cannot get it to skip even when explicitly passing it skip from the command line:

```
(my.project) bash-3.2$ isort --skip /Users/gaffney/workspace/my.project/app/my-project/x/gen/constants.py --check-only app/my-project/x/gen/constants.py
ERROR: /Users/gaffney/workspace/my.project/app/my-project/x/gen/constants.py Imports are incorrectly sorted.
```

**Comment by timothycrosley** [comment]
Hi @gaffney,

isort no longer skips items directly passed in from the command line, due to the confusion this caused. In general, in your example, both saying explicitly that you want to sort something, and also explicitly don't want to sort it leads to some ambiguity. For example, there used to be a default to skip `__init__.py`, but then when people ran `isort __init__.py` it wouldn't do anything, even though they explicitly asked it to. The skips now, intentionally, only affects recursive or plugin based usage. If you have a .isort.cfg with that skip in it and run `isort . --recursive` it should be skipped. 

Thanks!

~Timothy

**Comment by gaffney** [comment]
> The skips now, intentionally, only affects recursive or plugin based usage.

👍 `--recursive` did it. The issue was that we were doing `find blah | xargs isort`.

Guessing this is a result of not reading the docs closely enough 😄

**Comment by timothycrosley** [comment]
So glad to hear it's working for you now! Could also very well be a case of not writing enough docs as well! I'll add a question flag to this to make sure I know I recheck its documentation status.

Thanks!

~Timothy
